// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfyKfrHwNdS4wp-9OUOvCbfal_u5dr9YA',
    appId: '1:678232814328:web:2567d57364d8d63490410d',
    messagingSenderId: '678232814328',
    projectId: 'sample-3dd7c',
    authDomain: 'sample-3dd7c.firebaseapp.com',
    storageBucket: 'sample-3dd7c.firebasestorage.app',
    measurementId: 'G-FSX81RXHLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqfxtftCSe4Z25l0dDgTq7uywJCZ4LJ_o',
    appId: '1:678232814328:android:721b2a603a431c4d90410d',
    messagingSenderId: '678232814328',
    projectId: 'sample-3dd7c',
    storageBucket: 'sample-3dd7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_nf-1RL1rUZblER-a3y829yZ-gkN5yo',
    appId: '1:678232814328:ios:8ded480de1b39f0790410d',
    messagingSenderId: '678232814328',
    projectId: 'sample-3dd7c',
    storageBucket: 'sample-3dd7c.firebasestorage.app',
    iosBundleId: 'com.example.textapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_nf-1RL1rUZblER-a3y829yZ-gkN5yo',
    appId: '1:678232814328:ios:8ded480de1b39f0790410d',
    messagingSenderId: '678232814328',
    projectId: 'sample-3dd7c',
    storageBucket: 'sample-3dd7c.firebasestorage.app',
    iosBundleId: 'com.example.textapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfyKfrHwNdS4wp-9OUOvCbfal_u5dr9YA',
    appId: '1:678232814328:web:e4d12d1eeef7de3790410d',
    messagingSenderId: '678232814328',
    projectId: 'sample-3dd7c',
    authDomain: 'sample-3dd7c.firebaseapp.com',
    storageBucket: 'sample-3dd7c.firebasestorage.app',
    measurementId: 'G-X8BBRTEJY0',
  );
}
